name: CI

on: push
#  pull_request:
#    branches:
#      - develop
#      - 'release-**'

jobs:
  runs-ci:
    uses: dvsa/des-workflow-actions/.github/workflows/ci-backend.yaml@env-creataion
    with:
      dynamodb: true
    secrets:
      DES_ACCESS_TOKEN: ${{ secrets.DES_ACCESS_TOKEN }}
